def site_settings_processor(request):
	context_dictionary = {
		# 'root_url': 'jpark.pythonanywhere.com',
		'root_url': '127.0.0.1:8000',
		'admin_name': 'superuser',
		'company_name': 'Personal WebIT',
		'footer_copyright': 'Personal WebIT, 2014',
		'logo_file_name': 'images/logo.png',
		'site_email': 'jaredjamespark@gmail.com',
		# if email changes, update misc_pages/email.html
		'company_phone_text': '602-429-9029',
		'company_phone_link': '16024299029',
		'yelp_id': 'barefoot-pools-pool-service-and-repair-phoenix',
		'editable_profile_field_label_list': ['image', 'address', 'city', 'zipcode', 'phone'],
		'meta_content': 'Web design with an emphasis on mobile compatibility and data-driven processes.',
		'meta_keywords': 'Web design, website design, web hosting, internet host',
		'navbar_link1_name': '#portfolio',
		'navbar_link1_text': 'PORTFOLIO',
		'navbar_link2_name': '#services',
		'navbar_link2_text': 'SERVICES',
		'navbar_link3_name': '#about',
		'navbar_link3_text': 'ABOUT',
		'navbar_link4_name': '#contact',
		'navbar_link4_text': 'CONTACT',
		'hero_image': 'images/this_is_going_too_far.jpg',
		'main_image_header_text': "",
		'main_image_content_text': 'The business is out there, I can help you find it. Let\'s talk about how I can help your business grow.',
		'main_image_button_text': 'Take your business to the next level.',
		'main_image_button_link_name': 'contact',
		'homepage_content_top': 'Personalized web solutions for your small business.',
		'homepage_content_quote': '"Personal WebIT saved me thousands on my website. I couldn\'t be happier with the final product."',
		'homepage_content_quote_name': 'Alvin W',
		'img1_file': 'images/responsive.jpg',
		'img1_alt': 'Responsive Design',
		'img1_title': 'Mobile-first Design',
		'img1_text': "4 of 10 internet searches occur from tablet and phone devices. Capture visitors no matter how they find you with mobile-first design. Click this area to see for yourself.",
		'img1_link_name': 'index',
		'img2_file': 'images/sales_cycle.jpg',
		'img2_alt': 'Clean customized forms',
		'img2_title': 'Customized forms',
		'img2_text': "Create customized forms to capture the information you need in order to maximize your sales opportunities. Click this area to see for yourself.",
		'img1_is_popup': True,
		'img2_is_modal': True,
		'img2_link_name': '#contact_modal',
		'img3_file': 'images/professional-woman.jpg',
		'img3_alt': 'User Accounts',
		'img3_title': 'User Accounts',
		'img3_text': "Custom user accounts create endless opportunites to streamline your operations, including billing, scheduling, purchases, and more. Click this area to create an account and take a look at some possibilities for your website.",
		'img3_link_name': 'auth_login',
		'left_sidebar_img_file': 'images/awful_sidebar.png',
		'default_testimonial': '"Personal WebIT saved me thousands on my website. I couldn\'t be happier with the final product." - Alvin W.',
		'unique_content_title': 'Instant 10% Discount!',
		'unique_content_text': 'Sign up today and receive a coupon for a 10% discount on your next order. Also receive exclusive monthly offers and regular updates with our latest developments.',
		'unique_content_link_name': 'auth_login',
		'unique_content_button_text': 'Sign Up Now',
	}
	return(context_dictionary)